attorney_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_list), 
    path('details/<int:attorney_id>', views.details),
    path('add/', views.add), 
    path('create/', views.create), 
    path('update/<int:attorney_id>', views.update), 
    path('post/ajax/attorney', views.post_attorney, name="post_attorney"),
]

audit_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_list), 
    path('details/<int:audit_id>', views.details),
    path('add/', views.add), 
    path('create/', views.create), 
    path('update/<int:audit_id>', views.update), 
]

audit_project/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import views  # this will include a page to select which application you want to use

urlpatterns = [
    # We need to create a path to select the correct application
    #   I intend this to include several useful applications for the City of Boise
    path('', include('manager_app.urls')),
    path('manager/', include('manager_app.urls')),
    path('attorney/', include('attorney_app.urls')),
    path('audit/', include('audit_app.urls')),
    path('admin/', admin.site.urls),
]

# Add Django site authentication urls for:
# accounts/ login/ [name='login']
# accounts/ logout/ [name='logout']
# accounts/ password_change/ [name='password_change']
# accounts/ password_change/done/ [name='password_change_done']
# accounts/ password_reset/ [name='password_reset']
# accounts/ password_reset/done/ [name='password_reset_done']
# accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/ reset/done/ [name='password_reset_complete']
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

attorney_app/models.py
from django.db import models
from manager_app.models import Manager
from audit_app.models import AuditType

# Create your models here.
class Attorney(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    is_active = models.BooleanField(default=True)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE, related_name="attorneys")
    # audit_type = models.ForeignKey(AuditType, on_delete=models.CASCADE, related_name="attorneys")
    # case_audits is a list of audits done using this audit type - from the CaseAudit class
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    # this is used for the console and debugging purposes in the "shell"
    def __repr__(self):
        return f"Attorney Name: {self.first_name} {self.last_name}"

    # This will be used to display information when editing and creating attorneys
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

attorney_app/forms.py
from .models import Attorney
from manager_app.models import Manager
from audit_app.models import AuditType
from django import forms
# import datetime

class AttorneyForm(forms.ModelForm):
    # empty_label could also include my own custom test as a default selected value, but
    #   I am choosing "None" to prevent us from selecting an invalid manager
    manager= forms.ModelChoiceField(queryset=Manager.objects.all(), empty_label=None)
    # Get the list of default audit types
    # audit_types = forms.ModelChoiceField(queryset=AuditType.objects.all(), empty_label=None)
    # audit_types = [
    #     { "id": "1", "name": "PTC" },
    #     { "id": "2", "name": "DV" },
    #     { "id": "3", "name": "DUI" },
    # ]
        
    def __init__(self, *args, **kwargs):
        super(AttorneyForm, self).__init__(*args, **kwargs)

        # adding a form control class to each form input to enable bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Attorney 

        # include only 3 fields that exist in the Attorney Model to create form controls
        # fields = ("first_name", "last_name", "manager", "audit_types")
        fields = ("first_name", "last_name", "manager")


class AttorneyDetailForm(forms.ModelForm):
    # empty_label could also include my own custom test as a default selected value, but
    #   I am choosing "None" to prevent us from selecting an invalid manager
    manager = forms.ModelChoiceField(queryset=Manager.objects.all(), empty_label=None)
    # Get the list of default audit types
    # audit_types = forms.ModelChoiceField(queryset=AuditType.objects.all(), empty_label=None)
    # audit_types = [
    #     { "id": "1", "name": "PTC" },
    #     { "id": "2", "name": "DV" },
    #     { "id": "3", "name": "DUI" },
    # ]
        
    def __init__(self, *args, **kwargs):
        super(AttorneyDetailForm, self).__init__(*args, **kwargs)

        # adding a form control class to each form input to enable bootstrap
        for name in self.fields.keys():
            if name == "is_active":
                self.fields[name].widget.attrs.update({
                    "class": "col-sm-1",
                    "style": "width:20px;height:20px",
                })
            else:
                self.fields[name].widget.attrs.update({
                    "class": "form-control col-sm-8",
                })

    class Meta:
        model = Attorney 

        # include only 3 fields that exist in the Attorney Model to create form controls
        # fields = ("first_name", "last_name", "manager", "audit_types")
        fields = ("first_name", "last_name", "manager", "is_active")

attorney_app/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core import serializers
from .forms import AttorneyForm, AttorneyDetailForm
from .models import Attorney

# Create your views here.
def view_list(request):
    print("in attorney view_list")
    attorneys = Attorney.objects.all()
    form = AttorneyForm()
    context = {
        "attorneys": attorneys,
        "form": form,
    }
    return render(request, "attorney_list.html", context)

def details(request, attorney_id):
    print(f"in attorney details: {attorney_id}")
    # Get the attorney that matches this id
    attorney = Attorney.objects.get(id = attorney_id)
    # print(f"\tattorney details: {attorney}")
    form = AttorneyDetailForm(instance=attorney)

    context = {
        "is_add_attorney": False,
        "attorney": attorney,
        "form": form,
    }
    return render(request, "attorney_details.html", context)

def post_attorney(request):
    if request.is_ajax and request.method == "POST":
        # get the form data and assign it as a form object
        form = AttorneyForm(request.POST)

        # now use the built in form validation to verify our data passed in with the POST
        if form.is_valid():
            print("form is valid - creating attorney")
            # we can now process the data that came in the POST dictionary...but we access the "clean" data
            #   using the form.cleaned_data attribute / property
            attorney_exists = Attorney.objects.filter(first_name = form.cleaned_data['first_name'], last_name = form.cleaned_data['last_name'])
            if len(attorney_exists) > 0:
                print(f"Attorney already exists - attorney id: {attorney_exists[0].id}")
                return JsonResponse({"error": "That atorney already exists"}, status = 400)

            # save this in the database and assign the returned instance of the manager object to a variable
            instance = form.save()

            # serialize the data in a json format
            json_instance = serializers.serialize('json', [instance, ])
            # print(f"instance id just created: {instance.id}")
            print(f"Attorney json just created: {json_instance}")

            # send the serialized instance back to the client
            return JsonResponse({"instance": json_instance}, status = 200)
        else:
            # form wasn't valid, let them try again
            return JsonResponse({"error": form.errors}, status = 400)

    return JsonResponse({"error": "An unknown error occured while posting the new Attorney"}, status = 400)

def add(request):
    print("in attorney add")
    form = AttorneyForm()

    context = {
        "is_add_attorney": True,
        "form": form
    }
    return render(request, "attorney_details.html", context)

def create(request):
    print("in attorney create")
    if request.method == "POST":
        # get the form data and assign it as a form object
        form = AttorneyForm(request.POST)

        # now use the built in form validation to verify our data passed in with the POST
        if form.is_valid():
            print("form is valid - creating attorney")
            # we can now process the data that came in the POST dictionary...but we access the "clean" data
            #   using the form.cleaned_data attribute / property
            attorney_exists = Attorney.objects.filter(first_name = form.cleaned_data['first_name'], last_name = form.cleaned_data['last_name'])
            if len(attorney_exists) > 0:
                print(f"That attorney already exists - attorney id: {attorney_exists[0].id}")
                # redirect to the attorney that already exists
                return redirect(f"/attorney/details/{attorney_exists[0].id}")

            # save this in the database and assign the returned instance of the manager object to a variable
            instance = form.save()
            print(f"instance id just created: {instance.id}")
            return redirect(f"/attorney/details/{instance.id}")
        else:
            # form wasn't valid, let them try again
            print("Form is invalid - Try again!")
            # send the form back to show the errors as well as repopulate with the data they entered
            return render(request, "/attorney/add", {"form": form})

    # Since this is not a post request, redirect them to the attorney list
    return redirect("/attorney/")
    
# update the attorney object and save to DB
def update(request, attorney_id):
    print("in attorney update")
    if request.method == "POST":
        attorney = Attorney.objects.get(id = attorney_id)

        # get the form data and apply it to the instance and then assign it as a form object
        form = AttorneyDetailForm(request.POST, instance=attorney)

        # now use the built in form validation to verify our data passed in with the POST
        if form.is_valid():
            print("form is valid - updating attorney")
            
            # save this in the database and assign the returned instance of the manager object to a variable
            instance = form.save()
            return redirect(f"/attorney/details/{instance.id}")
        else:
            # form wasn't valid, let them try again
            print("Form is invalid - Try again!")
            # send the form back to show the errors as well as repopulate with the data they entered
            return render(request, f"/attorney/details/{attorney_id}", {"form": form})

    # Since this is not a post request, redirect them to the attorney list
    return redirect("/attorney/")

attorney_app/templates/attorney_details.html
{% extends "_audit_base.html" %}

{% block head %}
<title>Attorney Details</title>
{% endblock %}

{% block content %}
  <div class="row mb-3">
    <div class="col">
      {% if is_add_attorney %}
        <h2>New Attorney</h2>
      {% else %}
        <h2>{{attorney.first_name}} {{attorney.last_name}}</h2>
      {% endif %}
    </div>
    <!-- <div class="dropdown">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        Dropdown button
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Link 1</a>
        <a class="dropdown-item" href="#">Link 2</a>
        <a class="dropdown-item" href="#">Link 3</a>
      </div>
    </div> -->
    <div class="col-sm-4">
      <a href="/attorney/">Return to Attorney List</a>
    </div>
  </div>
  <!-- Display the details for a specific attorney in text boxes to update them or add them if this is to create a attorney -->
  <div class="row">
    <div class="col">
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <div class="col-sm-12 col-lg-10">
        {% if is_add_attorney %}
        <form method="POST" action="/attorney/create/" class="w-60">
        {% else %}
        <form method="POST" action="/attorney/update/{{attorney.id}}" class="w-60">
        {% endif %}
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row form-inline">
            {{ field.errors }}
            <label class="col-sm-3 justify-content-sm-end">{{ field.label }}</label>
            {{ field }}
          </div>
          {% endfor %}
          <div class="form-group text-center">
            {% if is_add_attorney %}
              <button type="submit" class="btn btn-success">Add</button>
            {% else %}
              <button type="submit" class="btn btn-success">Update</button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- <div class="row">
    <div class="col">
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <div class="col-sm-12 col-lg-10">
        {% if is_add_attorney %}
        <form method="POST" action="/attorney/create/" class="w-60">
        {% else %}
        <form method="POST" action="/attorney/update/{{attorney.id}}" class="w-60">
        {% endif %}
          {% csrf_token %}
          <div class="form-group row">
            <label for="first_name" class="col-sm-3 col-form-label text-sm-right">First Name</label>
            <div class="col-sm-8">
              <input type="text" id="first_name" name="first_name" class="form-control" value="{{attorney.first_name}}" />
            </div>
          </div>
          <div class="form-group row">
            <label for="last_name" class="col-sm-3 col-form-label text-sm-right">Last Name</label>
            <div class="col-sm-8">
              <input type="text" id="last_name" name="last_name" class="form-control" value="{{attorney.last_name}}" />
            </div>
          </div>
          <div class="form-group row">
            <label for="manager" class="col-sm-3 col-form-label text-sm-right">Manager</label>
            <div class="col-sm-8">
              <select id="manager" name="manager" class="col-sm-8 pl-1 browser-default" size="4">
                <option value="0">Select Manager</option>
                {% for manager in managers %}
                  <option value="{{manager.id}}" {% if manager.id == attorney.manager_id %} checked {% endif %}} >{{manager.first_name}} {{manager.last_name}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label for="audit_type" class="col-sm-3 col-form-label text-sm-right">Default Audit Type</label>
            <div class="col-sm-8">
              <select id="audit_type" name="audit_type" class="col-sm-8 pl-1 browser-default" size="4">
                <option value="0">Select Audit Type</option>
                {% for audit_type in audit_types %}
                  <option value="{{audit_type.id}}">{{audit_type.name}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-3"></div>
            <div class="col-sm-1">
              <input type="checkbox" id="is_active" name="is_active" value="is_active"
                {% if attorney.active %} checked {% endif %} />
            </div>
            <div class="col-sm-3">
              <label for="is_active" class="col col-form-label text-left">Active</label>
            </div>
          </div>
          <div class="form-group">
            {% if is_add_attorney %}
              <button type="submit" class="btn btn-success float-right">Add</button>
            {% else %}
              <button type="submit" class="btn btn-success float-right">Update</button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
  </div> -->
{% endblock %}

attorney_app/templates/attorney_list.html
{% extends "_audit_base.html" %}

{% block head %}
<title>Attorney List</title>
{% endblock %}

{% block content %}
  <div class="row mb-3">
    <div class="col">
      <h2>Attorneys</h2>
    </div>
    <!-- <div class="col-sm-3">
      <button class="btn btn-primary mx-3" onclick="window.location.href='/attorney/add';">Add Attorney</button>
    </div> -->
  </div>

  <div class="container-fluid">
    <form id="attorney-form">
      <div class="row">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group col-4">
          <label class="col-12">{{ field.label }}</label>
          {{ field }}
        </div>
        {% endfor %}
      </div>
      <div class="row justify-content-center">
        <input type="submit" class="btn btn-primary" value="Create Attorney" />
      </div>
    <form>
  </div>
  <hr />

  <div class="row my-4">
    <div class="col">
      <div class="container-fluid">
        <table class="table table-striped table-sm" id="attorneys-table">
          <thead>
            <tr>
              <th>Attorney Name</th>
              <th>Views</th>
              <th>Active</th>
            </tr>
          </thead>
          <tbody>
            {% for attorney in attorneys %}
            <tr>
              <td><a href="/attorney/details/{{attorney.id}}">{{attorney.first_name}} {{attorney.last_name}}</a></td>
              <td>
                <a href="/attorney/summary/{{attorney.id}}">Summary</a> |
                <a href="/attorney/audits/{{attorney.id}}">Audits</a>
              </td>
              <td>{{attorney.is_active}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}


{% block javascript %}
<script>
  // On submiting the form, send the POST (ajax) request to the server 
  // after successfull submission, display the object
  $("#attorney-form").submit(function (e) {
    // preventing page reload and all other default actions
    e.preventDefault();

    // serialize the data for sending the form data to the server
    var serializedData = $(this).serialize();

    // make the POST ajax call - explicitly sending a POST request to the "named" URL
    $.ajax({
      type: 'POST',
      url: "{% url 'post_attorney' %}",
      data: serializedData,
      success: function (response) {
        // after successfully the creating object, we need to do multiple things
        // 1. clear the form of the previously submitted data
        $("#attorney-form").trigger('reset');
        
        // 2. set the focus to first name input 
        $("#id_first_name").focus();

        // display the new manager in the table
        var instance = JSON.parse(response["instance"]);

        // use the first instance returned (it should only be one anyways)
        var fields = instance[0]["fields"];
        var id = instance[0]["pk"]

        // add this manager to the top of the list of managers
        //    These are written so that if the value is empty, we add an empty string to the TD
        $("#attorneys-table tbody").prepend(
          `<tr>
          <td><a href="/attorney/details/${id}">${fields["first_name"]||""} ${fields["last_name"]||""}</a></td>
          <td>
            <a href="/attorney/summary/{{attorney.id}}">Summary</a> |
            <a href="/attorney/audits/{{attorney.id}}">Audits</a>
          </td>
          <td>${fields["is_active"]||""}</td>
          </tr>`
        )},
        // <td>{{attorney.created_at | date:"Y-m-d"}}</td>

      error: function (response) {
        // alert the error if any occured
        alert(response["responseJSON"]["error"]);
      }
    })
  })
</script>

{% endblock javascript %}